#!/usr/bin/env python

import argparse
import math
import sys

def add_times(list_of_times):
    total_ms = 0

    for time in list_of_times:
        try:
            minutes, seconds, frames = time.split(':')
        except ValueError:
            print('Argument "%s" is invalid for adding' % (time))
            sys.exit(1)

        total_ms += int(minutes) * 60 * 1000
        total_ms += int(seconds) * 1000
        total_ms += (int(frames) / 75) * 1000

    minutes = math.floor(total_ms / 60000)
    remainder_ms = total_ms % 60000
    seconds = math.floor(remainder_ms / 1000)
    remainder_ms = remainder_ms % 1000
    frames = round((remainder_ms / 1000) * 75, 0)

    return '%02d:%02d:%02d' % (minutes, seconds, frames)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Calculate total CDDA time for use a in CUE sheet')

    parser.add_argument('times', metavar='TIMES',
                        nargs='+', help='times to add in HH:SS:FF where FF is frames (75 FPS in CDDA)')

    args = parser.parse_args()

    print(add_times(args.times))
