#!/usr/bin/env python2

import eyeD3
from eyeD3.frames import ImageFrame, FrameException
import sys
import pprint

if len(sys.argv) != 3:
    print 'Missing cover file name'
    sys.exit(1)

if len(sys.argv) == 2:
    print 'Missing MP3 file name'
    sys.exit(1)

eyeD3.utils.ITUNES_COMPAT = 1

tag = eyeD3.Tag()

try:
    tag.link(sys.argv[2])

    tag.removeImages()
    tag.removeComments()

    tag.addImage(ImageFrame.FRONT_COVER, sys.argv[1])
except Exception as e:
    print 'Error: ' + e.strerror
    sys.exit(1)
