#!/usr/bin/env bash
usage() {
    echo "Usage: $0 -j DEVICE" >&2
    echo "DEVICE is ALSA device after hw: prefix like 0,0 or 'Audio'." >&2
}

main() {
    local -r device=$1
    [ -z "$device" ] && usage && return 1
    mapfile -t supported_ffmpeg_formats < <(ffmpeg -formats 2>&1 | grep -F PCM | awk '{print $2}' |
        sort -u)
    echo "$device"
    for format in "${supported_ffmpeg_formats[@]}"; do
        for rate in 8000 11025 16000 22025 32000 44100 48000 88200 96000 176400 192000 \
            352800 384000; do
            out=$(ffmpeg -f alsa -acodec "pcm_${format}" -ar "$rate" -i "hw:${device}" 2>&1)
            if grep -q 'Device or resource busy' <<< "$out"; then
                echo "Device is in use, likely by Pipewire. Set the device profile to Off." >&2
                return 1
            fi
            if grep -q 'Input/output error' <<< "$out" || ! grep -q "${rate} Hz" <<< "$out"; then
                continue
            fi
            echo "    pcm_${format} @ ${rate} Hz"
        done
    done
}

main "$@"
