#!/usr/bin/env python
from typing import Sequence
import sys


def strip_non_ascii(k: Sequence[str]) -> str:
    return ''.join(x for x in k if ord(x) < 128)


def main() -> int:
    if len(sys.argv) > 1:
        lines = sys.argv[1:]
    else:
        lines = sys.stdin.readlines()
    original = ''.join(x.strip() for x in lines)
    stripped = ''.join(strip_non_ascii(x.strip()) for x in lines)
    if len(original) != len(stripped):
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
