#!/usr/bin/env python

import sys

def strip_non_ascii(k):
    return ''.join([x for x in k if ord(x) < 128])

if __name__ == '__main__':
    if len(sys.argv) > 1:
        lines = sys.argv[1:]
    else:
        lines = sys.stdin.readlines()

    original = ''.join([x.strip() for x in lines])
    stripped = ''.join([strip_non_ascii(x.strip()) for x in lines])

    if len(original) != len(stripped):
        sys.exit(1)
