#!/usr/bin/env bash

usage() {
    echo "Usage: $0 <exe file> <icon> <icon index>"
}

(test -z "$1" || test -z "$2" || test -z "$3") && usage && exit 1

EXE="$1"
ICO="$2"
ICO_INDEX="$3"

printf "[Autorun]\nopen=$EXE\nicon=$EXE,$ICO_INDEX\n" > Autorun.inf
unix2dos Autorun.inf &> /dev/null
