#!/usr/bin/env bash
set -e

find . -type f \( -iname ".*~" -o \
                  -iname ".*DS_Store" -o \
                  -iname "*.swp" \) \
    -ls -delete
find ~ -maxdepth 1 -type f \( -name 'java_error*.log' -o \
                              -name 'qphotorec.log' \) \
    -ls -delete
find ~ -maxdepth 1 -type d -name 'oradiag_*' -exec rm -vfR {} \;
