#!/usr/bin/env bash
# For Gentoo systems only. Run as root.
main() {
    set -e
    local -r v=$(readlink /usr/src/linux | sed -re 's/^linux-//')
    for i in /lib/modules/*; do
        if [ -d "$i" ] && [[ "$i" != *"${v}"* ]]; then
            rm -fR "$i"
        fi
    done
    for i in /usr/src/linux-*; do
        if [ -d "$i" ] && [[ "$(basename "$i")" != "linux-${v}" ]]; then
            rm -fR "$i"
        fi
    done
}
main
