#!/usr/bin/env php
<?php
namespace Curl2Php;

function array_to_php_array_string(array $arr)
{
    $ret = json_encode($arr);
    $ret = str_replace('\\/', '/', $ret);
    $ret = str_replace('","', "\",\n    \"", $ret);

    $ret = "\n" . '    '.substr($ret, 1, -1) . ",\n";

    return '[' . str_replace('"', "'", $ret) . ']';
}

/**
 * Main class.
 */
class Curl2PhpMain
{
    /**
    * Entry point.
    *
    * @param integer $argc Argument count.
    * @param array   $argv Argument array.
    *
    * @return integer
    */
    public static function main(int $argc, array $argv)
    {
        $headers = [];
        $cookie = $postData = '';
        $errorMessage = $url = null;
        $lastWasHeaderPos = $lastWasDataPos = false;
        $stripAcceptEncodingHeader = true;

        // Only -H, --header, and --data are supported
        foreach (array_slice($argv, 1) as $i => $arg) {
            if ($lastWasHeaderPos) {
                $lastWasHeaderPos = false;
                continue;
            }

            if ($lastWasDataPos) {
                $lastWasDataPos = false;
                continue;
            }

            if ($arg === '-H' || $arg === '--header') {
                if (isset($argv[$i + 2])) {
                    $parts = explode(':', $argv[$i + 2], 2);

                    if (count($parts) !== 2) {
                        $errorMessage = ('Invalid header argument. Header ' .
                                         'must be of format: "Header-Name: ' .
                                         'EncodedValue"');
                        break;
                    }

                    $parts[0] = strtolower($parts[0]);

                    if ($stripAcceptEncodingHeader &&
                        $parts[0] === 'accept-encoding') {
                        continue;
                    }

                    if ($parts[0] === 'cookie') {
                        $cookie = $parts[1];
                        continue;
                    }

                    $headers[] = $parts[0] . ':' . $parts[1];
                }

                $lastWasHeaderPos = true;
                continue;
            }

            if ($arg === '--data') {
                if (isset($argv[$i + 1])) {
                    $postData = $argv[$i + 1];
                }
            }

            if ($url === null) {
                $url = filter_var(
                    $arg,
                    FILTER_VALIDATE_URL,
                    FILTER_NULL_ON_FAILURE
                );
            }
        }

        if ($errorMessage) {
            fprintf(STDERR, $errorMessage."\n");

            return 1;
        }

        if ($url === null) {
            fprintf(STDERR, 'No URL was given'."\n");

            return 1;
        }

        $args = [$url];
        $format = [
            '<?php',
            "\$ch = curl_init('%s');\n",
            'curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);',
        ];

        if ($cookie) {
            $args[] = $cookie;
            $format[] = 'curl_setopt($ch, CURLOPT_COOKIE, \'%s\');';
        }
        if ($headers) {
            $args[] = array_to_php_array_string($headers);
            $format[] = 'curl_setopt($ch, CURLOPT_HTTPHEADER, %s);';
        }
        if ($postData) {
            $args[] = $postData;
            $format[] = 'curl_setopt($ch, CURLOPT_POSTFIELDS, \'%s\');';
        }

        $format[] = "// curl_setopt(\$ch, CURLOPT_HEADER, true);\n";
        $format[] = "\$data = curl_exec(\$ch);\n";
        $format[] = "if (\$data[strlen(\$data) - 1] != \"\\n\") {";
        $format[] = "    \$data .= \"\\n\";";
        $format[] = "}";
        $format[] = "print(\$data);\n";

        vprintf(join("\n", $format), $args);

        return 0;
    }
}

exit(Curl2PhpMain::main($argc, $argv));
