#!/usr/bin/env bash

cmd=open
if ! command -v open >/dev/null 2>&1; then
    cmd=xdg-open
fi
orig=$(git remote get-url origin)
if [ -n "$orig" ]; then
    "$cmd" "$(sed -r -e 's#^git@#https://#' \
                   -e 's#\.(com|org)\:#.\1/#' \
                   -e 's/\.git$//' <<< "$orig")"
fi
