#!/usr/bin/env bash
main() {
    if [ -z "$1" ]; then
        echo "Usage: $0 FILE [THRESHOLD]"
    fi

    local -r in_file="$1"
    local -r threshold=${2:-40}
    local -r convert_output=$(convert "$in_file" -colorspace hsb -resize 1x1 txt:-)

    if ! grep -F -q 'hsb' <<< "$convert_output"; then
        echo 'Error reading file' >&2
        return 1
    fi

    value=$(tail -n 1 <<< "$convert_output" |
        perl -pe 's/.*\s+hsb\([0-9]+(?:\.[0-9]+)?%,[0-9]+(?:\.[0-9]+)?%,([0-9]+(\.[0-9]+))?%\)/$1/' |
        awk '{print int($1+0.5)}')

    if ((value >= threshold)); then
        return 1
    fi
}

main "$@"
