#!/usr/bin/env python
from typing import Any, Dict, Optional, Sequence, cast
import sys

from pydbus import SessionBus


def toggleInhibit(inhibit_key: Optional[int] = None) -> Optional[int]:
    bus = SessionBus()
    notifications = bus.get("org.freedesktop.Notifications",
                            "/org/freedesktop/Notifications")
    if notifications.Inhibited:
        return cast(int, notifications.UnInhibit(inhibit_key))
    return toggleInhibit(cast(int, notifications.Inhibit('*', 'None', {})))


def main() -> int:
    toggleInhibit()
    return 0


if __name__ == '__main__':
    sys.exit(main())
