#!/usr/bin/env python
from os.path import expanduser
from typing import Final, Optional, cast
import sys
import time

from pydbus import SessionBus

KEY_FILE: Final[str] = expanduser('~/.cache/toggle-inhibit-key')


def toggle_inhibit() -> Optional[int]:
    bus = SessionBus()
    notifications = bus.get('org.freedesktop.Notifications',
                            '/org/freedesktop/Notifications')
    if notifications.Inhibited:
        print('Enabling notifications', file=sys.stderr)
        with open(KEY_FILE) as fp:
            return cast(Optional[int],
                        notifications.UnInhibit(int(fp.read().strip())))
    with open(KEY_FILE, 'w+') as fp:
        print(f'Saving key to {fp.name}', file=sys.stderr)
        key = cast(Optional[int], notifications.Inhibit('*', 'None', {}))
        fp.write(f'{key}\n')
        time.sleep(10)
        return key


def main() -> int:
    toggle_inhibit()
    return 0


if __name__ == '__main__':
    sys.exit(main())
