#!/bin/sh

for i in ifuse fusermount rsync; do
  which "$i" 2>&1 > /dev/null
  test $? -ne 0 &&  echo "$i must be in \$PATH" && exit 1
done

MOUNTDIR=$(tempfile -p isync)
IFUSE=$(which ifuse)
FUSERMOUNT=$(which fusermount)
RSYNC=$(which rsync)

cmd="$IFUSE $MOUNTDIR"
photos_dir="$MOUNTDIR/DCIM/100APPLE/"
target_dir=

while getopts 'u:t:h' OPTION; do
  case $OPTION in
    u)
      cmd="$cmd -u $OPTARG"
      ;;

    t)
      target_dir="$OPTARG"
      ;;

    h)
      echo "Usage: $0 [-u UDID] -t DIRECTORY"
      exit 1
      ;;

    ?)
      echo "Usage: $0 [-u UDID] -t DIRECTORY"
      exit 1
      ;;
  esac
done

if [ ! "$target_dir" ]; then
  echo 'Target directory argument -t is required'
  exit 1
elif [ ! -d "$target_dir" ]; then
  echo "$target_dir is not a valid directory"
  exit 1
fi

cmd="$cmd -o ro"

rm -f $MOUNTDIR
mkdir $MOUNTDIR

$cmd

if [ $? -ne 0 ]; then
  echo 'Failed to mount!'
  rm -fR $MOUNTDIR
  exit 1
fi

$RSYNC --progress --force --delete-before -a "$photos_dir" "$target_dir"
status=$?

if [ $status -ne 0 ]; then
  echo 'Something went wrong during syncing'
  status=1
fi

$FUSERMOUNT -u $MOUNTDIR

if [ $? -ne 0 ]; then
  echo 'Failed to unmount normally. Lazily umounting ...'
  fusermount -u -z $MOUNTDIR
  status=1
fi

rm -fR $MOUNTDIR

exit $status
