#!/usr/bin/env python
from collections.abc import Mapping
from typing import Any, Final
import json
import sys

import yaml

YD_ARGS: Final[Mapping[str, Any]] = {'default_flow_style': False, 'indent': 2}


def main() -> int:
    # argv mode
    if len(sys.argv) >= 2:
        for arg in sys.argv[1:]:
            try:
                with open(arg, encoding='utf-8') as f:
                    print(yaml.dump(json.loads(f.read().strip()), **YD_ARGS))
            except FileNotFoundError:
                return 1
        return 0
    # stdin mode
    for arg in sys.stdin.readlines():
        print(yaml.dump(json.loads(arg.strip()), **YD_ARGS))
    return 0


if __name__ == '__main__':
    sys.exit(main())
