#!/usr/bin/env python
from os import chdir, getcwd, listdir, remove as rm, rename
from os.path import basename, dirname, isdir, realpath
from typing import Iterator, List
from zipfile import ZipFile
import argparse
import re
import subprocess as sp
import sys


def extract_rar_from_zip(zfile: ZipFile) -> Iterator[str]:
    rars = (x for x in zfile.namelist() if re.search(r'\.r(?:ar|\d{2})$', x))
    for x in rars:
        zfile.extract(x)
    return rars


def unrar_x(rar: List[str]) -> None:
    sp.check_call(['unrar', 'x', '-y', rar[0]])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('directories', nargs='+')
    args = parser.parse_args()
    _dir: str
    for _dir in args.directories:
        if not isdir(_dir):
            print(f'Directory argument {_dir} is invalid', file=sys.stderr)
            return 1
    for _dir in args.directories:
        last = getcwd()
        chdir(_dir)
        zip_listing = frozenset(
            ZipFile(x) for x in listdir('.') if x.endswith('.zip'))
        if len(zip_listing) == 0:
            print(f'No zip files found. Skipping directory {_dir}',
                  file=sys.stderr)
            continue
        _rar_list = [extract_rar_from_zip(x) for x in zip_listing]
        extracted = [x for y in _rar_list for x in y]
        # Only need the .rar
        rar = [x for x in extracted if x.endswith('.rar')]
        unrar_x(rar)
        pdf = [x for x in listdir('.') if x.endswith('.pdf')]
        if len(pdf) > 1:
            print(
                'More than one PDF extracted. Not sure what to do. Skipping '
                f'directory {_dir}',
                file=sys.stderr)
            continue
        with open(pdf[0], 'rb') as f:
            if f.read(4) != b'%PDF':
                print(
                    '.pdf file extracted but is not a PDF. Skipping '
                    f'directory {_dir}',
                    file=sys.stderr)
                continue
        pdf_name = basename(dirname(realpath(pdf[0])))
        target_name = f'../{pdf_name}.pdf'
        rename(pdf[0], target_name)
        for x in extracted:
            rm(x)
        chdir(last)
    return 0


if __name__ == '__main__':
    sys.exit(main())
