#!/usr/bin/env python

import sys
from urllib.parse import urlparse, parse_qs, parse_qsl, unquote

try:
    if sys.argv[1] is False:
        print('Usage: %s URL' % sys.argv[0])
        sys.exit(1)
except IndexError:
    print('Usage: %s URL' % sys.argv[0])
    sys.exit(1)

parsed = urlparse(sys.argv[1])

if parsed.query == '':
    print('Invalid URL')
    sys.exit(1)

query = parse_qs(parsed.query)

try:
    print(unquote(query['RD_PARM1'][0]))
except Exception:
    print('Invalid URL (no RD_PARM1 parameter)')
    sys.exit(1)
