#!/usr/bin/env python
from typing import Dict, Final, List, Optional, Sequence, Tuple
import argparse
import os
import subprocess as sp
import sys

MODULES_RECOMMENDED_TO_KEEP: Final[Tuple[str, ...]] = (
    'ahci',
    'snd-usb-audio',
    'usb-storage',
    'usbfs',
)


def main() -> None:
    if os.geteuid() == 0:
        print('It is actually preferable to run this as non-root user', file=sys.stderr)
    parser: Final[argparse.ArgumentParser] = argparse.ArgumentParser()
    parser.add_argument('-i', '--ignore-modules', nargs='*')
    parser.add_argument('--no-recommended', action='store_true')
    args: Final[argparse.Namespace] = parser.parse_args()
    recommended = (MODULES_RECOMMENDED_TO_KEEP if not args.no_recommended else [])
    ignored_modules: Optional[List[str]] = args.ignore_modules
    all_ignored_modules: Final[Sequence[str]] = ((ignored_modules + list(recommended))
                                                 if ignored_modules else recommended)
    items_dict: Dict[str, List[str]] = {}
    with sp.Popen(('hwinfo',), stdout=sp.PIPE, text=True) as p:
        enabled = False
        while not p.poll():
            if p.stdout and (line := p.stdout.readline().strip()):
                if 'sysfs driver list end' in line:
                    break
                if 'sysfs driver list' in line:
                    enabled = True
                    continue
                if enabled:
                    k, v = [x.strip() for x in line.split(': ', 2)]
                    try:
                        items_dict[k].append(v)
                    except KeyError:
                        items_dict[k] = [v]
    for item in sorted(k for k, v in items_dict.items()
                       if len(v) == 1 and 'module =' in v[0] and k not in all_ignored_modules):
        print(item)


if __name__ == '__main__':
    main()
