#!/usr/bin/env bash

image="$1"
mount_point="$2"
fs="${3:-ext4}"

if [ -z "${image}" ]; then
    echo "Usage: $0 image mount_point [FILESYSTEM]"
    exit 1
fi

if (($(mount | grep -c "on ${mount_point}") >= 1)); then
    echo "Warning: ${mount_point} is already in use. Umounting..."
    umount-chroot "${mount_point}"
fi

mount -t "${fs}" "${image}" "${mount_point}" -o rw
mount -t proc none "${mount_point}/proc"

for i in dev sys tmp; do
    mount -o bind "/$i" "${mount_point}/$i"
done

for i in pts shm; do
    if [[ -d "/dev/$i" ]]; then
        mount -o bind "/dev/$i" "${mount_point}/dev/$i"
    fi
done

if [[ -d /usr/portage ]]; then
    mount -o bind /usr/portage "${mount_point}/usr/portage"
fi
