#!/usr/bin/env bash
set -e

for i in "$@"; do
    if [ -f "${i%.*}.info.json" ]; then
        AtomicParsley "$i" --overWrite --meta-uuid json file "${i%.*}.info.json"
        rm "${i%.*}.info.json"
    fi
done
