#!/usr/bin/env python
from base64 import standard_b64encode
from datetime import datetime
from os import unlink as rm, utime
from os.path import splitext
from shutil import copyfile
from typing import Any, AnyStr, Sequence, TextIO, Tuple, Union
import json
import re
import subprocess as sp
import sys

from typing_extensions import Final

CUSTOM_ATOM_NAME: Final[str] = 'json'
MIMETYPE: Final[str] = 'application/json'
TAG_DESCRIPTION: Final[str] = 'youtube-dl metadata'
MP4BOX_REM_ITEM_CMD: Final[Tuple[str, ...]] = (
    'MP4Box',
    '-rem-item',
    '1',
    '',  # MP4 filename
)
# https://sourceforge.net/p/gpac/discussion/327349/thread/6d010474/
MP4BOX_SET_META_CMD: Final[Tuple[str, ...]] = (
    'MP4Box',
    '-set-meta',
    'mp21',
    '',  # MP4 filename
)
MP4BOX_WRITE_CMD_TEMPLATE: Final[Tuple[str, ...]] = (
    'MP4Box', '-add-item',
    ':name=youtube-dl metadata:mime=application/json:encoding=utf8', '')
ID3_TEXT_FRAME = 'TXXX'
ID3TED_REMOVE_FRAME_TEMPLATE: Final[Tuple[str, ...]] = (
    'id3ted',
    '--preserve-times',
    '--remove',
    ID3_TEXT_FRAME,
    '',  # MP3 filename
)
ID3TED_WRITE_CMD_TEMPLATE: Final[Tuple[str,
                                       ...]] = ('id3ted', '--preserve-times',
                                                '-3', '--TXXX', '', '')
MKVPROPEDIT_WRITE_CMD_TEMPLATE: Final[Tuple[str, ...]] = (
    'mkvpropedit',
    '',  # MKV filename
    '--attachment-name',
    'info.json',
    '--add-attachment')
UPLOAD_DATE_FORMAT = '%Y%m%d'


def quiet_subprocess_check_call(args: Sequence[str], **kwargs: Any) -> None:
    try:
        arg: Union[int, TextIO] = sp.DEVNULL
    except AttributeError:
        arg = open('/dev/null')
    if 'check' in kwargs:
        kwargs.pop('check')
    kwargs['stdout'] = arg
    kwargs['stderr'] = arg
    sp.run(args, check=True, **kwargs)


def set_date(path: str, json_str: bytes) -> None:
    data = json.loads(json_str.decode())
    try:
        upload_date = data['upload_date']
    except KeyError:
        return
    if not isinstance(upload_date, str):
        return
    seconds = datetime.strptime(upload_date, UPLOAD_DATE_FORMAT).timestamp()
    utime(path, times=(seconds, seconds))


def mp4box_add_json(filename: str, json_filename: str) -> bool:
    cmd = list(MP4BOX_REM_ITEM_CMD)
    cmd[3] = filename
    try:
        quiet_subprocess_check_call(cmd)
    except sp.CalledProcessError:
        pass

    cmd = list(MP4BOX_SET_META_CMD)
    cmd[3] = filename
    quiet_subprocess_check_call(cmd)

    better_json_filename = 'info.json'
    copyfile(json_filename, better_json_filename)

    cmd = list(MP4BOX_WRITE_CMD_TEMPLATE)
    cmd[2] = f'{better_json_filename}{cmd[2]}'
    cmd[3] = filename
    quiet_subprocess_check_call(cmd)

    rm(better_json_filename)
    with open(json_filename, 'rb') as f:
        set_date(filename, f.read())
    return True


def id3ted_add_json(filename: str, json_filename: str) -> bool:
    cmd = list(ID3TED_REMOVE_FRAME_TEMPLATE)
    cmd[-1] = filename
    quiet_subprocess_check_call(cmd)
    cmd = list(ID3TED_WRITE_CMD_TEMPLATE)
    with open(json_filename, 'rb') as f:
        new_json = f.read()
    encoded = standard_b64encode(new_json).decode()
    cmd[-2] = f'{encoded}:{TAG_DESCRIPTION}'
    cmd[-1] = filename
    quiet_subprocess_check_call(cmd)
    set_date(filename, new_json)
    return True


def mkvpropedit_add_json(filename: str, json_filename: str) -> bool:
    cmd = list(MKVPROPEDIT_WRITE_CMD_TEMPLATE)
    cmd[1] = filename
    cmd.append(json_filename)
    quiet_subprocess_check_call(cmd)
    with open(json_filename, 'rb') as f:
        set_date(filename, f.read())
    return True


def isfile(path: Union[AnyStr, int]) -> bool:
    try:
        with open(path):
            pass
    except IOError:
        return False
    return True


def main() -> int:
    mp4_ext_regex = re.compile(r'\.(?:mp4|m4[pabrv])$')
    mp3_ext_regex = re.compile(r'\.mp3')
    mkv_ext_regex = re.compile(r'\.mkv')
    for arg in sys.argv[1:]:
        json_filename = f'{splitext(arg)[0]}.info.json'
        if not isfile(json_filename):
            continue
        can_delete = False
        if re.search(mp4_ext_regex, arg):
            can_delete = mp4box_add_json(arg, json_filename)
        elif re.search(mp3_ext_regex, arg):
            can_delete = id3ted_add_json(arg, json_filename)
        elif re.search(mkv_ext_regex, arg):
            can_delete = mkvpropedit_add_json(arg, json_filename)
        if can_delete:
            rm(json_filename)
    return 0


if __name__ == '__main__':
    sys.exit(main())
