#!/usr/bin/env python
from os.path import basename, isdir, realpath
from shutil import rmtree
import sys


def _rename_and_trash(dir_: str) -> None:
    try:
        with open(f'{dir_}/{basename(dir_).lower()}.mkv', 'rb') as _in:
            new_file = realpath(f'{dir_}/../{basename(dir_)}.mkv')
            with open(new_file, 'wb+') as out:
                out.write(_in.read())
            rmtree(dir_)
    except OSError:
        pass


def main() -> int:
    for x in sys.argv[1:]:
        x = realpath(x)
        if not isdir(x):
            continue
        _rename_and_trash(x)
    return 0


if __name__ == '__main__':
    sys.exit(main())
