#!/usr/bin/env python
from os.path import basename, isdir, realpath
from shutil import rmtree
from sys import argv


def _rename_and_trash(d):
    look_for = '{}/{}.mkv'.format(d, basename(d).lower())

    try:
        with open(look_for, 'rb') as _in:
            new_file = realpath('{}/../{}.mkv'.format(d, basename(d)))
            with open(new_file, 'wb+') as out:
                out.write(_in.read())
            rmtree(d)
    except IOError:
        pass


if __name__ == '__main__':
    for x in argv[1:]:
        x = realpath(x)
        if not isdir(x):
            continue

        _rename_and_trash(x)
