#!/usr/bin/env bash
main() {
    if [ -z "$1" ]; then
        echo "Usage: $0 HOST [PORT]" >&2
        return 1
    fi
    local -r remote_host="$1"
    local -r remote_port="${2:-443}"
    exec 6>&1
    exec > "$remote_host"
    echo | openssl s_client -connect "${remote_host}:${remote_port}" 2>&1 |
        sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
    certutil -d "sql:$HOME/.pki/nssdb" -A -t TC -n "$remote_host" -i "$remote_host"
    exec 1>&6 6>&-
    rm "$remote_host"
}

main "$@"
