#!/usr/bin/env python
from pathlib import Path
import logging
import plistlib
import sys

HIGH_RES_KEY = 'NSHighResolutionCapable'


def main():
    log = logging.getLogger('main')
    for fin in sys.argv[1:]:
        p = Path(fin).joinpath('Contents', 'Info.plist')
        if not p.exists():
            log.info(f'Skipping {fin} (Info.plist not found)')
            continue
        with p.open('rb') as f:
            data = plistlib.load(f)
            if HIGH_RES_KEY in data:
                log.info(f'Skipping {fin} (key already set)')
                continue
            data[HIGH_RES_KEY] = True
        with p.open('wb') as f:
            plistlib.dump(data, f, sort_keys=False)
        p.touch()
        log.info(f'Rewrote Info.plist for {fin}')


if __name__ == '__main__':
    main()
