#!/usr/bin/env sh
if command -v sw_vers &>/dev/null; then
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
        -kill \
        -seed \
        -r -f -v \
        -domain local \
        -domain user \
        -domain system
fi
