#!/usr/bin/env python
import re
import sys

from yt_dlp.utils import sanitize_filename


def main(s: str) -> int:
    try:
        res = sanitize_filename(s, restricted=True)
    except IndexError:
        return 1
    if not (res := res.strip()):
        return 1
    print(
        re.sub(r'([a-z0-9])\-s\-', r'\1s-', re.sub(r'\.-', '-', re.sub(r'[_\-]+', '-',
                                                                       res.lower()))))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1]))
