#!/usr/bin/env python
import re
import sys

from youtube_dl.utils import sanitize_filename


def main(s: str) -> int:
    try:
        r = sanitize_filename(s, restricted=True)
    except IndexError:
        return 1
    r = r.strip()
    if not r:
        return 1
    print(re.sub(r'[_\-]+', '-', r.lower()))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1]))
