#!/usr/bin/env bash
DASHARG=
DEST="${BASH_ARGV[0]}"
files=()
rm_args=()
scp_args=()

while getopts "hc:F:i:l:o:P:S:1246BCEpqrv" OPTION; do
    case $OPTION in
        1 | 2 | 4 | 6 | B | C | E | p | q | r | v)
            [ -z "$DASHARG" ] && DASHARG="-"
            DASHARG="$DASHARG$OPTION"
            [ "$OPTION" = "v" ] && rm_args+=("-v")
            [ "$OPTION" = "r" ] && rm_args+=("-R")
            ;;

        c)
            scp_args+=("-c $OPTARG")
            ;;

        F)
            scp_args+=("-F $OPTARG")
            ;;

        i)
            scp_args+=("-i $OPTARG")
            ;;

        l)
            scp_args+=("-l $OPTARG")
            ;;

        o)
            scp_args+=("-o $OPTARG")
            ;;

        P)
            scp_args+=("-P $OPTARG")
            ;;

        S)
            scp_args+=("-S $OPTARG")
            ;;

        h)
            scp -h 2>&1 | grep -v illegal | sed -e 's/scp/smv/g'
            exit 1
            ;;

        ?)
            scp -h
            exit 1
            ;;
    esac
done

if [ -n "$DASHARG" ]; then
  scp_args+=("$DASHARG")
fi
for f in "$@"; do
    if [[ "$f" = -* ]] || [[ "$f" = "$DEST" ]]; then
        continue
    fi
    scp_args+=("$f")
    files+=("$f")
done
if ((${#files[@]} == 0)) || [ -z "$DEST" ]; then
    scp -h 2>&1 | grep -v illegal | sed -e 's/scp/smv/g'
    exit 1
fi
scp_args+=("${DEST}")
((${#rm_args[@]} == 0)) && unset rm_args

if scp "${scp_args[@]}"; then
    rm "${rm_args[@]}" "${files[@]}"
fi
