#!/usr/bin/env python

import argparse
import sys

ENGLISH_MODE = 0x1
JAPANESE_MODE = 0x10
CHINESE_MODE = 0x100
ARABIC_MODE = 0x1000

# non-strict, not including words like below, forms of to be, forms of
#   you/he/etc, or words like 'call'
stop_words = [
    'a',
    'an',
    'and',
    'at',
    'by',
    'de',  # mainly for Spanish and French
    'el',  # Spanish
    'for',
    'from',
    'il',  # Italian
    'in',
    'into',
    'la',  # Spanish/French/Italian
    'lo',  # Italian
    'of',
    'off',
    'on',
    'or',
    'per',
    #'so',
    'te',  # Spanish/French
    #'than',
    'the',
    #'then',
    #'this',
    'to',
    #'too',
    'via',
    'with',
    'within',
    'without',
]

# Only really common ones
japanese_particles = [
    'de',
    'e',
    'ga',
    'ha',
    'ka',
    'kana',
    'ne',
    'ni',
    'no',
    'to',
    'wa',
    'wo',
]

chinese_particles = [
    'de',
    'ge',
    'he',
    'le',
    'ma',
]

# NOTE This list is not yet complete
arabic_stops = [
    'al',

    'li',
    'laka',
    'lahu',

    'fi',
    'fiya',
    'fika',
    'fihi',

    'bi',
    'biha',
    'bika',
    'bihi',

    'ila',
    'ilayya',
    'ilayka',
    'ilayhi',

    'ala',
    'alayya',
    'alayka',
    'alayhi',

    'maa',
    'mai',
    'maaka',
    'maahu',

    'min',
    'minni',
    'minka',
    'minhu',

    'an',
    'anni',
    'anka',
    'anhu',

    'wa',
]

mode_map = {
    ENGLISH_MODE: stop_words,
    CHINESE_MODE: chinese_particles,
    JAPANESE_MODE: japanese_particles,
    ARABIC_MODE: arabic_stops,
}


def lower_stop(words, modes=[ENGLISH_MODE]):
    words = words.strip().title().split()
    title = [words[0]]

    for mode in modes:
        to_lower_case_array = mode_map[mode]
        index = 1
        for word in words[1:]:
            if word.lower() in to_lower_case_array:
                word = words[index] = word.lower()

            try:
                title[index] = word
            except IndexError:
                title.append(word)

            index += 1

    return ' '.join(title)

parser = argparse.ArgumentParser(description='Title fixer for various '
                                 'languages. Defaults to English mode. If any '
                                 'option is specified without -e, English mode'
                                 ' is disabled.')
parser.add_argument('titles', metavar='TITLE', type=argparse.FileType('r'),
                    default=sys.stdin, nargs='?', help='Titles to process')
parser.add_argument('-e', dest='mode', action='append_const',
                    const=ENGLISH_MODE, help='Enable English mode')
parser.add_argument('-c', dest='mode', action='append_const',
                    const=CHINESE_MODE, help='Enable Chinese mode')
parser.add_argument('-j', dest='mode', action='append_const',
                    const=JAPANESE_MODE, help='Enable Japanese mode')
parser.add_argument('-a', dest='mode', action='append_const',
                    const=ARABIC_MODE, help='Enable Arabic mode')
args = parser.parse_args()

if args.mode is None:
    args.mode = [ENGLISH_MODE]

[print(lower_stop(title, args.mode)) for title in args.titles]
