#!/usr/bin/env python

import sys

# argv mode
if len(sys.argv) >= 2:
    for arg in sys.argv[1:]:
        print(arg.strip())
    sys.exit()

# stdin mode
[print(arg.strip()) for arg in sys.stdin.readlines()]
