#!/usr/bin/env bash
set -e

input="$1"
_bn=$(basename "$input")
out="${_bn%.*}-5ch.mkv"

cfe=$(mktemp __cfe.XXXXXXXXXX --suffix=.wav)
left=$(mktemp __left.XXXXXXXXXX --suffix=.wav)
right=$(mktemp __right.XXXXXXXXXX --suffix=.wav)
noaud=$(mktemp __noaud.XXXXXXXXXX --suffix=.mkv)

deltmp() {
    rm -f "$cfe" "$left" "$right" "$noaud"
}
trap deltmp EXIT

ffmpeg -y -i "$input" -ac 1 "$cfe"
ffmpeg \
    -y \
    -i "$input" \
    -map_channel 0.1.0 "$left" \
    -map_channel 0.1.1 "$right" || \
        ffmpeg \
            -y \
            -i "$input" \
            -map_channel 0.0.0 "$left" \
            -map_channel 0.0.1 "$right"
ffmpeg -y -i "$input" -c:v copy -an "$noaud"
ffmpeg \
    -y \
    -i "$noaud" \
    -i "$left" \
    -i "$right" \
    -i "$cfe" \
    -i "$left" \
    -i "$right" \
    -filter_complex '[1:a][2:a][3:a][4:a][5:a]amerge=inputs=5[aout]' \
    -map 0:0 \
    -map '[aout]' \
    -c:a aac \
    -c:v copy \
    "$out"
