#!/usr/bin/env python

import sys
from unidecode import unidecode

# argv mode
if len(sys.argv) >= 2:
    for arg in sys.argv[1:]:
        print(unidecode(arg.strip()))
    sys.exit()

# stdin mode
for arg in sys.stdin.readlines():
    print(unidecode(arg.strip()))
