#!/usr/bin/env bash
if [ -z "$1" ]; then
    echo "Usage: $0 DIR [DIR ...]" >&2
    exit 1
fi

for dir in "$@"; do
    if ! [ -d "$dir" ]; then
        echo "Bad argument: $dir" >&2
        continue
    fi

    pushd "$dir" || continue
    for i in *.zip; do
        ! [ -f "$i" ] && break
        unzip -o "$i"
    done
    rm -f ./*.diz ./*.DIZ
    outsfv=$(echo ./*.rar | sed -r -e 's/\.rar$/.sfv/')
    cksfv -q ./*.r[0-9][0-9] ./*.part*.rar ./*.rar 2> /dev/null > "$outsfv" || true
    rm -f ./*.zip
    popd || continue
done
