#!/usr/bin/env python
from typing import Iterable, Iterator
from urllib.parse import unquote_plus, urlparse
import argparse
import sys


def parse(values: Iterable[str],
          is_netloc: bool = False,
          encoding: str = 'utf-8',
          errors: str = 'replace') -> Iterator[str]:
    for x in values:
        val = unquote_plus(x, encoding=encoding, errors=errors)
        if is_netloc:
            val = urlparse(val).netloc.strip()
        yield val


def main() -> int:
    is_netloc = sys.argv[0].endswith('netloc')
    parser = argparse.ArgumentParser()
    parser.add_argument('-e', '--encoding', default='utf-8')
    parser.add_argument('-r', '--errors', default='replace')
    is_atty = sys.stdin.isatty()
    if is_atty:
        parser.add_argument('string', nargs='*')
    args = parser.parse_args()
    arg = args.string if is_atty else sys.stdin.readlines()
    for x in parse(arg,
                   is_netloc=is_netloc,
                   encoding=args.encoding,
                   errors=args.errors):
        print(x)
    return 0


if __name__ == '__main__':
    sys.exit(main())
