#!/usr/bin/env python
import argparse
import sys
try:
    from urllib import unquote_plus
except ImportError:
    from urllib.parse import unquote_plus


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-e', '--encoding', default='utf-8')
    parser.add_argument('-r', '--errors', default='replace')
    args = parser.parse_args()

    sys.stdout.write(unquote_plus(sys.stdin.read(),
                                  encoding=args.encoding,
                                  errors=args.errors))
