#!/usr/bin/env python
import argparse
import os
import sys
try:
    from urllib import unquote_plus
    from urllib2.urlparse import urlparse
except ImportError:
    from urllib.parse import urlparse, unquote_plus


def parse(values, is_netloc=False):
    for x in values:
        val = unquote_plus(x, encoding=args.encoding, errors=args.errors)
        if is_netloc:
            val = urlparse(val).netloc.strip()
        yield val

if __name__ == '__main__':
    is_netloc = sys.argv[0].endswith('netloc')
    parser = argparse.ArgumentParser()
    parser.add_argument('-e', '--encoding', default='utf-8')
    parser.add_argument('-r', '--errors', default='replace')
    is_atty = sys.stdin.isatty()

    if is_atty:
        parser.add_argument('string', nargs='*')

    args = parser.parse_args()
    arg = args.string if is_atty else sys.stdin.readlines()

    for x in parse(arg, is_netloc=is_netloc):
        print(x)
