#!/usr/bin/env python
from os.path import basename
import argparse
import logging
import sys

from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util import Retry
from requests.utils import dict_from_cookiejar
import requests

GET_URL = 'https://tools.usps.com/go/TrackConfirmAction'
POST_URL = ('https://tools.usps.com/go/TrackConfirmRequestUpdateAJAXAction'
            '.action')
NAME1_EMPTY_VALUE = 'not required'
MAX_RETRIES = 10
HEADERS = {
    'Accept-Language': 'en-US,en;q=0.8,en-GB;q=0.6',
    'Connection': 'keep-alive',
    'Accept': 'text/html,application/xhtml+xml,'
              'application/xml;q=0.9,*/*;q=0.8',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/66.0.3359.45 '
                  'Safari/537.36',
    'DNT': '1',
    'Pragma': 'no-cache',
    'Cache-Control': 'no-cache',
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser(basename(sys.argv[0]))
    parser.add_argument('tracking_number',
                        nargs='+',
                        metavar='TRACKING_NUMBER',
                        help='Tracking numbers')
    parser.add_argument('phone_number',
                        nargs=1,
                        metavar='PHONE_NUMBER',
                        help='Phone number to send SMS to (US only)')
    parser.add_argument('-d', '--debug', action='store_true')

    args = parser.parse_args()
    phone_number = args.phone_number[0]
    log = logging.getLogger('requests.packages.urllib3')
    formatter = logging.Formatter('%(asctime)s - %(name)s - '
                                  '%(levelname)s - %(message)s')
    channel = logging.StreamHandler(sys.stderr)

    log.setLevel(logging.DEBUG if args.debug else logging.ERROR)
    channel.setLevel(logging.DEBUG if args.debug else logging.ERROR)
    channel.setFormatter(formatter)
    log.addHandler(channel)

    http_adapter = HTTPAdapter(max_retries=MAX_RETRIES)
    session = requests.Session()

    session.mount('http://', http_adapter)
    session.mount('https://', http_adapter)
    session.headers = HEADERS

    if '-' not in phone_number:
        if phone_number[0] == '1' and len(phone_number) == 11:
            phone_number = phone_number[1:]
            log.debug('Removed leading 1')
        parts = [phone_number[i:i + 3] for i in range(0, 10, 3)]
        log.debug('Phone number parts: {}'.format(parts))
        phone_number = '-'.join(parts[0:3]) + parts[3]
        log.debug('Adjusted phone number: {}'.format(phone_number))

    for arg in args.tracking_number:
        r = session.get(GET_URL, params=dict(
            qtc_tLabels1=arg,
        ))
        r.raise_for_status()
        content = r.content.decode('utf-8')

        if 'could not locate the tracking information' in content:
            log.error('Failed with tracking number {}'.format(arg))
            continue

        data = dict(
            label=arg,
            textAll='on',
            textFuture='on',
            textToday='on',
            textDnd='on',
            textPickup='on',
            textOA='on',
            textAlert='on',
            email1=NAME1_EMPTY_VALUE,
            name1=NAME1_EMPTY_VALUE,
            smsNumber=phone_number,
            confirmSms='on',
        )
        log.debug('POST data: {}'.format(data))
        add_headers = {
            'X-Requested-With': 'XMLHttpRequest',
            'Referer': '{}?qtc_tLabels1={}'.format(GET_URL, arg),
        }
        r = session.post(POST_URL, data=data, headers=add_headers)
        r.raise_for_status()
        json = r.json()
        log.debug('JSON response: {}'.format(json))

        if json.get('textServiceError', None) != 'false':
            log.error('Failed with tracking number {}'.format(arg))
