#!/usr/bin/env python
from enum import IntEnum
from time import sleep
import fcntl
import os
import sys

CDROM_DRIVE_STATUS = 0x5326


class CDStatus(IntEnum):
    DISC_OK = 4
    DRIVE_NOT_READY = 3
    NO_DISC = 1
    NO_INFO = 0
    TRAY_OPEN = 2


def main() -> int:
    try:
        f = os.open(sys.argv[1], os.O_RDONLY | os.O_NONBLOCK)
    except IndexError:
        f = os.open('/dev/sr0', os.O_RDONLY | os.O_NONBLOCK)
    except OSError:
        print(f'open {sys.argv[1]}', file=sys.stderr)
        return 1
    try:
        sleep_time = float(sys.argv[2])
    except ValueError as e:
        print(e.args[0], file=sys.stderr)
        return 1
    except IndexError:
        sleep_time = 1
    s = -1
    try:
        while s != CDStatus.DISC_OK:
            s = fcntl.ioctl(f, CDROM_DRIVE_STATUS, 0)
            if s == CDStatus.NO_INFO:
                print('ioctl(CDROM_DRIVE_STATUS)', file=sys.stderr)
                return 1
            if s != CDStatus.DISC_OK:
                sleep(sleep_time)
    except KeyboardInterrupt:
        pass
    os.close(f)
    return s != CDStatus.DISC_OK


if __name__ == '__main__':
    sys.exit(main())
