#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
from functools import lru_cache
from os.path import basename
from typing import Optional
import argparse
import logging
import subprocess as sp
import sys
try:
    import argcomplete
except ImportError:
    argcomplete = None


TR_MAP = (
    ('　', ' '),
    ('…', '...'),
    ('！', '!'),
    ('？', '?'),
    ('～', '~'),
    ('（', '('),
    ('）', ')'),
    ('＂', '"'),
    ('＃', '#'),
    ('＄', '$'),
    ('％', '%'),
    ('＆', '&'),
    ('＇', "'"),
    ('＊', '*'),
    ('，', ','),
    ('－', '-'),
    ('．', '.'),
    ('／', '/'),
    ('０', '0'),
    ('１', '1'),
    ('２', '2'),
    ('３', '3'),
    ('４', '4'),
    ('５', '5'),
    ('６', '6'),
    ('７', '7'),
    ('８', '8'),
    ('９', '9'),
    ('：', ':'),
    ('；', ';'),
    ('＜', '<'),
    ('＝', '='),
    ('＞', '>'),
    ('？', '?'),
    ('＠', '@'),
    ('Ａ', 'A'),
    ('Ｂ', 'B'),
    ('Ｃ', 'C'),
    ('Ｄ', 'D'),
    ('Ｅ', 'E'),
    ('Ｆ', 'F'),
    ('Ｇ', 'G'),
    ('Ｈ', 'H'),
    ('Ｉ', 'I'),
    ('Ｊ', 'J'),
    ('Ｋ', 'K'),
    ('Ｌ', 'L'),
    ('Ｍ', 'M'),
    ('Ｎ', 'N'),
    ('Ｏ', 'O'),
    ('Ｐ', 'P'),
    ('Ｑ', 'Q'),
    ('Ｒ', 'R'),
    ('Ｓ', 'S'),
    ('Ｔ', 'T'),
    ('Ｕ', 'U'),
    ('Ｖ', 'V'),
    ('Ｗ', 'W'),
    ('Ｘ', 'X'),
    ('Ｙ', 'Y'),
    ('Ｚ', 'Z'),
    ('［', '['),
    ('＼', '\\'),
    ('］', ']'),
    ('＾', '^'),
    ('＿', '_'),
    ('｀', '`'),
    ('ａ', 'a'),
    ('ｂ', 'b'),
    ('ｃ', 'c'),
    ('ｄ', 'd'),
    ('ｅ', 'e'),
    ('ｆ', 'f'),
    ('ｇ', 'g'),
    ('ｈ', 'h'),
    ('ｉ', 'i'),
    ('ｊ', 'j'),
    ('ｋ', 'k'),
    ('ｌ', 'l'),
    ('ｍ', 'm'),
    ('ｎ', 'n'),
    ('ｏ', 'o'),
    ('ｐ', 'p'),
    ('ｑ', 'q'),
    ('ｒ', 'r'),
    ('ｓ', 's'),
    ('ｔ', 't'),
    ('ｕ', 'u'),
    ('ｖ', 'v'),
    ('ｗ', 'w'),
    ('ｘ', 'x'),
    ('ｙ', 'y'),
    ('ｚ', 'z'),
    ('｛', '{'),
    ('｜', '|'),
    ('｝', '}'),
    ('｟', '⸨'),
    ('｠', '⸩'),
    ('￠', '¢'),
    ('￡', '£'),
    ('￢', '¬'),
    ('￣', '‾'),
    ('￤', '|'),
    ('￥', '¥'),
    ('￦', '₩'),
)


@lru_cache()
def setup_logging_stdout(name: Optional[str] = None,
                         verbose: bool = False) -> logging.Logger:
    name = name if name else basename(sys.argv[0])
    log = logging.getLogger(name)
    log.setLevel(logging.DEBUG if verbose else logging.INFO)
    channel = logging.StreamHandler(sys.stdout)
    channel.setFormatter(logging.Formatter('%(message)s'))
    channel.setLevel(logging.DEBUG if verbose else logging.INFO)
    log.addHandler(channel)
    return log


def make_target(filename: str) -> str:
    for find, replace in TR_MAP:
        filename = filename.replace(find, replace)
    return filename


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Renames file names with full-width characters to normal '
        'width name. Please see `man mv` or `info coreutils \'mv invocation\'`'
        ' for option arguments')
    # ilm mv | grep -E '^‘\-' | cut -c 2- | sed -e "s/’$//"
    parser.add_argument('--backup')
    parser.add_argument('-b', action='store_true')
    parser.add_argument('-f', '--force', action='store_true')
    parser.add_argument('-i', '--interactive', action='store_true')
    parser.add_argument('-n', '--no-clobber', action='store_true')
    parser.add_argument('-u', '--update', action='store_true')
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument('--strip-trailing-slashes', action='store_true')
    parser.add_argument('-S', '--suffix')
    parser.add_argument('-t', '--target-directory')
    parser.add_argument('-T', '--no-target-directory', action='store_true')
    parser.add_argument('file', metavar='SOURCE', nargs=1, help='Source')
    if argcomplete:
        argcomplete.autocomplete(parser)
    args = parser.parse_args()
    log = setup_logging_stdout(verbose=args.verbose)
    special_values = (
        ('--backup', args.backup),
        ('--suffix', args.suffix),
        ('--target-directory', args.target_directory),
    )
    bool_args = (
        ('--backup', args.b),
        ('--force', args.force),
        ('--interactive', args.interactive),
        ('--no-clobber', args.no_clobber),
        ('--update', args.update),
        ('--strip-trailing-slashes', args.strip_trailing_slashes),
    )
    mv_args = []
    if args.b and args.backup:
        log.error('Cannot use -b and --backup simultaneously')
        return 1
    for arg, val in special_values:
        if isinstance(val, str):
            mv_args.append(f'{arg}={val}')
    for arg, val in bool_args:
        if val is True:
            mv_args.append(arg)
    command = ['mv'] + mv_args + [args.file[0], make_target(args.file[0])]
    log.info('Command: %s', ' '.join(command))
    try:
        p = sp.run(command,
                   stdout=sp.PIPE,
                   stderr=sp.PIPE,
                   encoding='utf-8',
                   check=True)
    except sp.CalledProcessError as e:
        log.error('STDOUT: %s', e.output)
        log.error('STDERR: %s', e.stderr)
        return e.returncode
    if '-v' in mv_args or '--verbose' in mv_args:
        log.info(p.stdout)
    return 0


if __name__ == '__main__':
    sys.exit(main())
