#!/usr/bin/env bash
usage() {
    echo "Usage: $0 <exe file> <icon> <icon index>" >&2
}
main() {
    local -r exe="$1"
    local -r ico_index="$3"
    printf "[Autorun]\nopen=%s\nicon=%s,%d\n" \
        "$exe" "$exe" "$ico_index" > Autorun.inf
    unix2dos Autorun.inf &> /dev/null
}
[ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] && usage && exit 1
main "$@"
