#!/usr/bin/env python
from functools import lru_cache
from os.path import basename
from pathlib import Path
from typing import Final
import logging
import plistlib
import sys

HIGH_RES_KEY: Final[str] = 'NSHighResolutionCapable'


@lru_cache
def setup_logging_stdout(name: str | None = None, verbose: bool = False) -> logging.Logger:
    name = name or basename(sys.argv[0])
    log = logging.getLogger(name)
    log.setLevel(logging.DEBUG if verbose else logging.INFO)
    channel = logging.StreamHandler(sys.stdout)
    channel.setFormatter(logging.Formatter('%(message)s'))
    channel.setLevel(logging.DEBUG if verbose else logging.INFO)
    log.addHandler(channel)
    return log


def main() -> int:
    log = setup_logging_stdout()
    for fin in sys.argv[1:]:
        path = Path(fin).joinpath('Contents', 'Info.plist')
        if not path.exists():
            log.warning('Skipping %s (Info.plist not found)', fin)
            continue
        with path.open('rb') as fp:
            data: dict[str, bool] = plistlib.load(fp)
            data[HIGH_RES_KEY] = True
        with path.open('wb') as fp:
            plistlib.dump(data, fp, sort_keys=False)
        log.info('Rewrote Info.plist for %s', fin)
        log.debug('Running `touch "%s"`', fin)
        Path(fin).touch()
    return 0


if __name__ == '__main__':
    sys.exit(main())
