#!/usr/bin/env bash
input="$1"
_bn=$(basename "$input")
out="${_bn%.*}-5ch.mkv"
cfe=$(mktemp __cfe.XXXXXXXXXX --suffix=.wav)
left=$(mktemp __left.XXXXXXXXXX --suffix=.wav)
right=$(mktemp __right.XXXXXXXXXX --suffix=.wav)
no_aud=$(mktemp __no_aud.XXXXXXXXXX --suffix=.mkv)
del_tmp() {
    rm -f "$cfe" "$left" "$right" "$no_aud"
}
trap del_tmp EXIT
ffmpeg -y -i "$input" -ac 1 "$cfe"
ffmpeg \
    -y \
    -i "$input" \
    -map_channel 0.1.0 "$left" \
    -map_channel 0.1.1 "$right" ||
    ffmpeg \
        -y \
        -i "$input" \
        -map_channel 0.0.0 "$left" \
        -map_channel 0.0.1 "$right"
ffmpeg -y -i "$input" -c:v copy -an "$no_aud"
ffmpeg \
    -y \
    -i "$no_aud" \
    -i "$left" \
    -i "$right" \
    -i "$cfe" \
    -i "$left" \
    -i "$right" \
    -filter_complex '[1:a][2:a][3:a][4:a][5:a]amerge=inputs=5[aout]' \
    -map 0:0 \
    -map '[aout]' \
    -c:a aac \
    -c:v copy \
    "$out"
